postgres:
  image: postgres:14.6-alpine
  ports:
    - '5432:5432'
  environment:
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'workdb123'
    POSTGRES_DB: 'work_db'
  volumes:
   - ./init:/docker-entrypoint-initdb.d/
